#!/usr/bin/env python3

"""VM side WireGuard Agent.

Runs as a systemd service inside the VM image.
Reads the network name from wireguard_network.json.

Workflow:
    1. Ensure keypair (primary.pem / primary.pub.pem)
    2. Load or create wireguard_network.json (with public key)
    3. If newly created -> upload to Host inventory
    4. Poll loop:
       a. Download wireguard_network.json from inventory -> save as wireguard_network_inv.json
       b. Compare timestamps -> merge data.network if newer
       c. Re-upload local config (public_keys protected)
       d. If assigned_ip exists -> generate wg.conf -> activate interface

Usage:
    python3 wg_agent.py
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
import time

from domain.wireguard.wg_data import WgNetworkConfig
from domain.wireguard.wg_config_builder import WgConfigBuilder
from domain.wireguard.wg_key_manager import WgKeyManager

# Default paths
DEFAULT_AGENT_CONFIG = "/opt/unitao/wg_agent.conf"
DEFAULT_INVENTORY_TOOL = "/opt/unitao-server-config/inventory_tool.py"
DEFAULT_WG_DIR = "/etc/wireguard"
DEFAULT_POLL_INTERVAL = 30

# Inventory filenames
INVENTORY_CONFIG_NAME = "wireguard_network"
INVENTORY_STATUS_NAME = "wireguard_network_status"
INVENTORY_INV_FILENAME = "wireguard_network_inv.json"


class WgAgent:
    """WireGuard Mesh Agent.

    Reads agent config (generated by install.py) to discover:
        - networkConfigPath -> wireguard_network.json path
        - inventoryTool     -> inventory_tool.py path
        - wgDir             -> WireGuard data directory
    """

    def __init__(self, agent_config_path: str = DEFAULT_AGENT_CONFIG):
        self._agent_config_path = agent_config_path
        self._network_config_path = None
        self._inventory_tool = DEFAULT_INVENTORY_TOOL
        self._wg_dir = DEFAULT_WG_DIR
        self._network = None
        self._key_manager = None
        self._wg_conf_path = None

    # -- Step 0: load agent config ------------------------------------------

    def load_agent_config(self):
        if not os.path.isfile(self._agent_config_path):
            raise FileNotFoundError(
                f"Agent config not found: {self._agent_config_path}\n"
                f"  Run install.py during image build."
            )
        with open(self._agent_config_path, "r") as f:
            agent_conf = json.load(f)
        self._network_config_path = agent_conf.get("networkConfigPath", None)
        if not self._network_config_path:
            raise KeyError(
                f"Missing [networkConfigPath] in {self._agent_config_path}"
            )
        self._inventory_tool = agent_conf.get("inventoryTool", self._inventory_tool)
        self._wg_dir = agent_conf.get("wgDir", self._wg_dir)
        print(f"  Agent config: {self._agent_config_path}")
        print(f"  Network config: {self._network_config_path}")

    # -- Step 1: ensure keypair ---------------------------------------------

    def _init_key_manager(self, network: str):
        self._network = network
        self._key_manager = WgKeyManager(self._network, self._wg_dir)
        self._wg_conf_path = os.path.join(self._wg_dir, f"{self._network}.conf")

    def ensure_keypair(self) -> tuple:
        return self._key_manager.generate_keypair(force=False)

    # -- inventory communication --------------------------------------------

    def _run_inventory_tool(self, *args) -> tuple:
        """返回 (success, stdout, stderr)。"""
        cmd = [sys.executable, self._inventory_tool] + list(args)
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            return result.returncode == 0, result.stdout, result.stderr
        except FileNotFoundError:
            print(f"  [WARN] inventory_tool not found: {self._inventory_tool}",
                  file=sys.stderr)
            return False, "", ""
        except subprocess.TimeoutExpired:
            print(f"  [WARN] inventory_tool timed out", file=sys.stderr)
            return False, "", ""

    def _inventory_get(self, filename: str) -> tuple | None:
        """返回 (data_dict, api_timestamp) 或 None。"""
        ok, stdout, stderr = self._run_inventory_tool("--get", filename)
        if not ok:
            return None, None
        # Parse API timestamp from inventory_tool output (on stdout)
        api_ts = None
        for line in (stdout + stderr).split("\n"):
            if line.startswith("Last modified:"):
                api_ts = line.split(":", 1)[1].strip()
                break
        # Parse JSON from stdout
        json_start = stdout.find("{")
        if json_start == -1:
            return None, None
        try:
            return json.loads(stdout[json_start:]), api_ts
        except json.JSONDecodeError:
            return None, None

    def _inventory_post(self, data: dict, name: str = None) -> bool:
        """POST data to inventory. `name` is added only for the API call."""
        payload = dict(data)
        payload["name"] = name if name else INVENTORY_CONFIG_NAME
        tmp = None
        try:
            tmp = tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", prefix="wg_agent_", delete=False
            )
            json.dump(payload, tmp)
            tmp.close()
            ok, _, _ = self._run_inventory_tool("--data", tmp.name)
            return ok
        finally:
            if tmp and os.path.exists(tmp.name):
                os.unlink(tmp.name)

    def _inventory_patch(self, filename: str, data: dict) -> bool:
        """PATCH an inventory file via curl (deep-merge, preserves other fields)."""
        inv_config_path = os.path.join(
            os.path.dirname(self._inventory_tool), "inventory.json"
        )
        try:
            with open(inv_config_path, "r") as f:
                inv_conf = json.load(f)
            host = inv_conf.get("hostApiUrl", "")
            vm_id = inv_conf.get("vmId", "")
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            return False

        if not host or not vm_id:
            return False

        url = f"{host}/api/v1/vms/{vm_id}/inventory/{filename}"
        tmp = None
        try:
            tmp = tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", prefix="wg_patch_", delete=False
            )
            json.dump(data, tmp)
            tmp.close()
            result = subprocess.run(
                ["curl", "-s", "-X", "PATCH", url,
                 "-H", "Content-Type: application/json",
                 "-d", f"@{tmp.name}"],
                capture_output=True, text=True, timeout=30,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False
        finally:
            if tmp and os.path.exists(tmp.name):
                os.unlink(tmp.name)

    def _collect_status(self) -> list:
        """Collect interface status. When up, includes recv/sent bytes from wg show."""
        if not self._key_manager.interface_exists(self._network):
            return [{"key": "state", "value": "down"}]

        recv = sent = 0
        try:
            r = subprocess.run(
                ["wg", "show", self._network, "transfer"],
                capture_output=True, text=True,
            )
            if r.returncode == 0:
                parts = r.stdout.strip().split()
                if len(parts) >= 2:
                    recv = parts[0]
                    sent = parts[1]
                elif len(parts) >= 4:
                    recv = f"{parts[0]} {parts[1]}"
                    sent = f"{parts[2]} {parts[3]}"
        except FileNotFoundError:
            pass

        return [
            {"key": "state", "value": "up"},
            {"key": "recv_bytes", "value": str(recv) if recv else "0"},
            {"key": "sent_bytes", "value": str(sent) if sent else "0"},
        ]

    def _report_status(self):
        """POST status to inventory as a separate file."""
        status = self._collect_status()
        ok = self._inventory_post(
            {"status": status},
            name=INVENTORY_STATUS_NAME,
        )
        if not ok:
            print(f"  [WARN] Failed to report status.", file=sys.stderr)

    # -- Step 2: local config management ------------------------------------

    def _ensure_local_config(self, public_key: str) -> WgNetworkConfig:
        """Load or create wireguard_network.json with public key."""
        if os.path.isfile(self._network_config_path):
            cfg = WgNetworkConfig.from_file(self._network_config_path)
            # Ensure public_key is up-to-date
            if cfg.primary_public_key != public_key:
                cfg._ensure_public_keys()[
                    WgNetworkConfig.Key.DATA_PUBLIC_KEYS_PRIMARY
                ] = public_key
                cfg.save_to_file(self._network_config_path)
                print(f"  Public key updated in {self._network_config_path}")
            return cfg
        else:
            print(f"  Creating initial {self._network_config_path} ...")
            cfg = WgNetworkConfig.create_initial(public_key)
            cfg.save_to_file(self._network_config_path)
            return cfg

    def _upload_config(self, config: WgNetworkConfig):
        """上传本地 wireguard_network.json 到 inventory（覆盖）。"""
        print(f"  Uploading config to inventory ...")
        ok = self._inventory_post(config.to_dict())
        if ok:
            print(f"  Config uploaded.")
        else:
            print(f"  [WARN] Failed to upload config.", file=sys.stderr)

    def _download_inv(self) -> tuple:
        """从 inventory 下载 wireguard_network.json，
        保存为 wireguard_network_inv.json。

        Returns:
            (WgNetworkConfig, api_timestamp) 或 (None, None)
        """
        data, api_ts = self._inventory_get(f"{INVENTORY_CONFIG_NAME}.json")
        if data is None:
            return None, None
        try:
            inv = WgNetworkConfig(data)
            inv_path = os.path.join(
                os.path.dirname(self._network_config_path),
                INVENTORY_INV_FILENAME,
            )
            inv.save_to_file(inv_path)
            return inv, api_ts
        except ValueError as e:
            print(f"  [WARN] Invalid inv config: {e}", file=sys.stderr)
            return None, None

    # -- Step 3: apply config -----------------------------------------------

    def apply_config(self, network_cfg: WgNetworkConfig, private_key: str) -> bool:
        if not network_cfg.has_network_config:
            print(f"  [WARN] No assigned_ip, cannot apply.", file=sys.stderr)
            return False

        conf_text = WgConfigBuilder.build_vm_config(
            network=network_cfg,
            private_key=private_key,
        )

        os.makedirs(os.path.dirname(self._wg_conf_path), exist_ok=True)
        with open(self._wg_conf_path, "w") as f:
            f.write(conf_text + "\n")

        iface = self._network
        if self._key_manager.interface_exists(iface):
            print(f"  Updating existing interface [{iface}] ...")
            return self._sync_conf()
        else:
            print(f"  Bringing up interface [{iface}] ...")
            return self._wg_quick_up()

    def _wg_quick_up(self) -> bool:
        try:
            result = subprocess.run(
                ["systemctl", "start", f"wg-quick@{self._network}"],
                capture_output=True, text=True,
            )
            if result.returncode != 0:
                print(f"  [ERROR] wg-quick up failed: {result.stderr.strip()}",
                      file=sys.stderr)
                return False
            print(f"  Interface [{self._network}] is up.")
            return True
        except FileNotFoundError:
            print(f"  [ERROR] wg-quick not found.", file=sys.stderr)
            return False

    def _sync_conf(self) -> bool:
        try:
            strip_result = subprocess.run(
                ["wg-quick", "strip", self._network],
                capture_output=True, text=True,
            )
            if strip_result.returncode != 0:
                print(f"  [WARN] wg-quick strip failed, falling back to restart.",
                      file=sys.stderr)
                return self._restart_interface()

            sync_path = os.path.join(
                os.path.dirname(self._wg_conf_path),
                f".{self._network}.sync.conf"
            )
            with open(sync_path, "w") as f:
                os.chmod(sync_path, 0o644)
                f.write(strip_result.stdout)

            sync_result = subprocess.run(
                ["wg", "syncconf", self._network, sync_path],
                capture_output=True, text=True,
            )
            os.unlink(sync_path)

            if sync_result.returncode != 0:
                print(f"  [WARN] wg syncconf failed, falling back to restart: {sync_result.stderr.strip()}",
                      file=sys.stderr)
                return self._restart_interface()
            print(f"  Interface [{self._network}] updated (syncconf).")
            return True
        except FileNotFoundError:
            print(f"  [ERROR] wg command not found.", file=sys.stderr)
            return False

    def _restart_interface(self) -> bool:
        try:
            subprocess.run(
                ["systemctl", "stop", f"wg-quick@{self._network}"],
                capture_output=True, text=True,
            )
        except FileNotFoundError:
            pass
        return self._wg_quick_up()

    # -- main loop ----------------------------------------------------------

    def run(self, poll_interval: int = DEFAULT_POLL_INTERVAL):
        print(f"=== WireGuard Agent ===\n")

        # 0. Load agent config
        print("[0/4] Loading agent config ...")
        self.load_agent_config()
        print(f"  Inventory tool: {self._inventory_tool}")

        # 1. Ensure keypair
        print("\n[1/4] Ensuring keypair ...")
        # FIXME: Hardcoded to "wg0" for now.
        # In the future, when multiple networks are supported,
        # use "wg{network_idx}" convention.
        self._init_key_manager("wg0")
        private_key, public_key = self.ensure_keypair()
        print(f"  Public key: {public_key[:16]}...")

        # 2. Load or create wireguard_network.json
        print("\n[2/4] Ensuring local config ...")
        network_cfg = self._ensure_local_config(public_key)
        print(f"  Primary public key in config: {network_cfg.primary_public_key[:16]}...")

        # 3. Upload to inventory (retry until success)
        print("\n[3/4] Uploading initial config to inventory ...")
        while True:
            ok = self._inventory_post(network_cfg.to_dict())
            if ok:
                print(f"  Config uploaded.")
                break
            print(f"  [WARN] Upload failed, retrying in 5s ...", file=sys.stderr)
            time.sleep(5)

        # 4. Poll loop — compare API file modification timestamps
        print(f"\n[4/4] Entering poll loop (interval={poll_interval}s) ...")
        applied = False
        last_modified = None

        while True:
            print(f"\n[{time.strftime('%H:%M:%S')}] Checking inventory ...")

            inv, api_ts = self._download_inv()

            if inv is None:
                print(f"  Inv config not available. Retrying in {poll_interval}s ...")
            else:
                if api_ts and api_ts != last_modified:
                    last_modified = api_ts
                    network_cfg = WgNetworkConfig.from_file(self._network_config_path)
                    prev_network = json.dumps(network_cfg._ensure_network(), sort_keys=True)
                    network_cfg.merge_network_from(inv, api_ts)
                    new_network = json.dumps(network_cfg._ensure_network(), sort_keys=True)
                    if prev_network != new_network:
                        network_cfg.save_to_file(self._network_config_path)
                        print(f"  Local config updated from inv.")
                        applied = False
                    else:
                        print(f"  API timestamp changed but content unchanged.")

                if network_cfg.has_network_config:
                    if not applied:
                        print(f"  Applying config ...")
                        if self.apply_config(network_cfg, private_key):
                            applied = True
                        else:
                            print(f"  [WARN] Failed to apply config, will retry.",
                                  file=sys.stderr)
                    else:
                        print(f"  Config unchanged, interface already up.")
                else:
                    print(f"  Waiting for assigned_ip ...")

            self._report_status()
            time.sleep(poll_interval)


# CLI

def main():
    parser = argparse.ArgumentParser(
        description="WireGuard Mesh Agent"
    )
    parser.add_argument(
        "--agent-config", type=str, default=DEFAULT_AGENT_CONFIG,
        help=f"Path to agent config (default: {DEFAULT_AGENT_CONFIG})",
    )
    parser.add_argument(
        "--poll-interval", type=int, default=DEFAULT_POLL_INTERVAL,
        help=f"Poll interval in seconds (default: {DEFAULT_POLL_INTERVAL})",
    )
    args = parser.parse_args()

    agent = WgAgent(agent_config_path=args.agent_config)
    agent.run(poll_interval=args.poll_interval)


if __name__ == "__main__":
    main()
